version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_YOUR_HOSTNAME=http://server:5000
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
